name: Build and Test JavaFX Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Java 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK distribution
          java-version: '23'
          cache: maven

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build project using Maven
      - name: Build with Maven
        run: mvn clean package

      # Run unit tests
      - name: Run unit tests
        run: mvn test
